### ISSUE TITLE
How to set username and password in mailenable web services

### ISSUE THREAD

**Issue by unosbaghaie** [eravse/MailEnable.DeleteAccount#1]
Hi
I want to add MailBox in mail enable . when I use this code 

           `MailEnableMailBoxSoap.Mailbox oMailBox = new MailEnableMailBoxSoap.Mailbox();
            oMailBox.Postoffice = "test.com";
            oMailBox.MailboxName = "mailbox";
            oMailBox.Limit = -1;
            oMailBox.RedirectAddress = "";
            oMailBox.RedirectStatus = 0;
            oMailBox.Status = 1;
            oMailBox.Host = "test.com";
            
           MailEnableMailBoxSoap.MailboxSoapClient mailboxSoap = new MailEnableMailBoxSoap.MailboxSoapClient(MailEnableMailBoxSoap.MailboxSoapClient.EndpointConfiguration.MailboxSoap12);
            mailboxSoap.ClientCredentials.Windows.ClientCredential = new NetworkCredential("postmaster@test.com", "123");
            mailboxSoap.ClientCredentials.Windows.AllowedImpersonationLevel = System.Security.Principal.TokenImpersonationLevel.Delegation;

            var vall = await mailboxSoap.AddMailboxAsync("test.com", "mailbox", 0, 0, 0, "");`

I get an error 

`MessageSecurityException: The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'Basic Realm="MailEnable"'.
`

Do you know how I can make web service calls?

**Comment by eravse** [comment]
Hello do you change Mail Enable Webservices addres in AppConfig  and it have a permission open local machine ?

**Comment by unosbaghaie** [comment]
no
How I can do it?

I just added its web services in .net core 2 and then make calls, then i get that error

**Comment by eravse** [comment]
@unosbaghaie  can you read https://www.mailenable.com/kb/content/article.asp?ID=ME020613 this article you can be give permission from administration panel from mail enable .

**Comment by unosbaghaie** [comment]
I have read it.  What I get is, call login first then create a mailbox and so on. but in my project any call to any method in web services, will prompt the username and password which I don't know how to supply. And causes that error

**Comment by eravse** [comment]
Ok i understand i will be check on my environment and will be back soon

**Comment by unosbaghaie** [comment]
thanks . I really appreciate that

**Comment by unosbaghaie** [comment]
hey
Just for your information, 
MailEnable web services are protected by URL authorization, I don't know how to pass credentials in this case

**Comment by eravse** [comment]
Hello @unosbaghaie  

Please check this article and update your config file . https://www.mailenable.com/kb/content/article.asp?ID=ME020463 when we write this code we didnt make any special authorization on mail enable.

**Comment by unosbaghaie** [comment]
thanks for your response

with changing authorization and authentication config in web.config file, it didn't work.
you know, it's URL authorization integrated with membership in MailEnable. 
When it prompts, it needs a Postoffice's sysadmin user (a MailEnable user which its type is sysAdmin). 

I wonder how their web services work!!

**Comment by eravse** [comment]
@unosbaghaie  do you work on remote computer ? or run on mail enable server ? you shoul be run on the server.

**Comment by unosbaghaie** [comment]
on the server in browser, it prompts for credential. 

But I didn't check calling a web service from c# inside the server.
let me do it, I will inform you about result.

thanks

**Comment by unosbaghaie** [comment]
the same error

`Unhandled Exception: System.AggregateException: One or more errors occurred. (Th
e HTTP request is unauthorized with client authentication scheme 'Anonymous'. Th
e authentication header received from the server was 'Basic Realm="MailEnable"'.
) ---> System.ServiceModel.Security.MessageSecurityException: The HTTP request i
s unauthorized with client authentication scheme 'Anonymous'. The authentication
 header received from the server was 'Basic Realm="MailEnable"'.
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncR
esult result)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[
] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayC
lass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at MailEnableSoap.Class1.Test() in C:\Users\Administrator\Desktop\WebSConsole
App\MailEnableSoap\Class1.cs:line 35
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at WebSConsoleApp.Program.Main(String[] args) in C:\Users\Administrator\Deskt
op\WebSConsoleApp\WebSConsoleApp\Program.cs:line 33`

**Comment by eravse** [comment]
i will check on net core version. This version only classic .net framework .
